name: 'Check lints'
description: 'Make sure the code emits no clippy and rustc lints'
inputs:
  toolchain:
    description: 'Rust toolchain to be used'
    default: 'stable'
  cargo-flags:
    description: 'Extra cargo flags, for enabling/disabling cargo features'
    default: ''
  rust-flags:
    description: 'Extra rustc flags, for enabling/disabling target features'
    default: ''
  cross-target-apt:
    description: 'For cross-compilation, set this to the target name used in ubuntu APT repositories and also set cross-target-rust'
    default: ''
  cross-target-rust:
    description: 'For cross-compilation, set this to the target name used in rustup and also set cross-target-apt'
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Rust compilation flags
      shell: bash
      run: |
        echo RUSTFLAGS="-D warnings ${{ inputs.rust-flags }}" >> $GITHUB_ENV

    - name: Install a cross-compiler using APT
      if: inputs.cross-target-apt != ''
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        version: 1.0
        packages: gcc-12-${{ inputs.cross-target-apt }}

    - name: Set up a Rust toolchain for native compilation
      if: inputs.cross-target-rust == ''
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: clippy

    - name: Set up a Rust toolchain for cross-compilation
      if: inputs.cross-target-rust != ''
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.cross-target-rust }}
        components: clippy

    - name: Configure Cargo to use the cross-compiler as a linker
      if: inputs.cross-target-apt != '' && inputs.cross-target-rust != ''
      shell: bash
      run: |
        echo "[target.${{ inputs.cross-target-rust }}]" > ~/.cargo/config.toml
        echo "linker = \"/usr/bin/${{ inputs.cross-target-apt }}-gcc-12\"" >> ~/.cargo/config.toml

    - name: Check clippy lints
      shell: bash
      run: |
        FLAGS="${{ inputs.cargo-flags }}"
        if [[ ${{ inputs.toolchain }} == 'nightly' ]]; then
          FLAGS="--features nightly ${FLAGS}"
        fi
        cargo clippy --workspace --all-targets ${FLAGS} -- -D warnings